#ifndef NOVA_WEBCACHE_H
#define NOVA_WEBCACHE_H

typedef struct {
    const char *slug;
    const char *label;
    const char *host;
    const char *url;
    const char *path;
    const char *captured_at;
    const char *content;
} nova_webcache_entry_t;

static const char nova_webcache_github_home[] =
    "# GitHub\n"
    "Titre: GitHub  Change is constant. GitHub keeps you ahead.  GitHub\n"
    "URL source: https://github.com\n"
    "Capture: 2026-04-13 18:12 UTC\n"
    "Mode: miroir texte de page web reelle pour le navigateur local\n"
    "\n"
    "GitHub Change is constant. GitHub keeps you ahead. GitHub\n"
    "Skip to content\n"
    "Navigation Menu\n"
    "Toggle navigation\n"
    "Sign in\n"
    "Platform\n"
    "DEVELOPMENT TOOLS\n"
    "GitHub Copilot\n"
    "Build and review code\n"
    "GitHub Spark\n"
    "Build and deploy apps\n"
    "GitHub Models\n"
    "Manage development templates\n"
    "MCP Registry\n"
    "New\n"
    "Integrate external tools\n"
    "DEVELOPER WORKFLOWS\n"
    "Actions\n"
    "Automate any workflow\n"
    "Codespaces\n"
    "Instant dev environments\n"
    "Issues\n"
    "Plan and track work\n"
    "Code Review\n"
    "Manage code changes\n"
    "APPLICATION SECURITY\n"
    "GitHub Advanced Security\n"
    "Find and fix vulnerabilities\n"
    "Code security\n"
    "Secure your code as you build\n"
    "Secret protection\n"
    "Stop leaks before they start\n"
    "EXPLORE\n"
    "Why GitHub\n"
    "Documentation\n"
    "Blog\n"
    "Changelog\n"
    "Marketplace\n"
    "View all features\n"
    "Solutions\n"
    "BY COMPANY SIZE\n"
    "Enterprises\n"
    "Small and medium teams\n"
    "Startups\n"
    "Nonprofits\n"
    "BY USE CASE\n"
    "App Modernization\n"
    "DevSecOps\n"
    "DevOps\n"
    "CI/CD\n"
    "View all use cases\n"
    "BY INDUSTRY\n"
    "Healthcare\n"
    "Financial services\n"
    "Manufacturing\n"
    "Government\n"
    "View all industries\n"
    "View all solutions\n"
    "Resources\n"
    "EXPLORE BY TOPIC\n"
    "Development\n"
    "Software Development\n"
    "Security\n"
    "View all topics\n"
    "EXPLORE BY TYPE\n"
    "Customer stories\n"
    "Events & webinars\n"
    "Ebooks & reports\n"
    "Business insights\n"
    "GitHub Skills\n"
    "SUPPORT & SERVICES\n"
    "Customer support\n"
    "Community forum\n"
    "Trust center\n"
    "Partners\n"
    "View all resources\n"
    "Open Source\n"
    "COMMUNITY\n"
    "GitHub Sponsors\n"
    "Fund open source developers\n"
    "PROGRAMS\n"
    "Security Lab\n"
    "Maintainer Community\n"
    "Accelerator\n"
    "GitHub Stars\n"
    "Archive Program\n"
    "REPOSITORIES\n"
    "Topics\n"
    "Trending\n"
    "Collections\n"
    ;

static const char nova_webcache_wikipedia_home[] =
    "# Wikipedia\n"
    "Titre: Wikipedia\n"
    "URL source: https://www.wikipedia.org\n"
    "Capture: 2026-04-13 18:12 UTC\n"
    "Mode: miroir texte de page web reelle pour le navigateur local\n"
    "\n"
    "Wikipedia\n"
    "The Free Encyclopedia\n"
    "English\n"
    "7,166,000+\n"
    "articles\n"
    "ea\n"
    "1,497,000+\n"
    "e ao\n"
    "Deutsch\n"
    "3.111.000+\n"
    "Artikel\n"
    "NNNo 1\n"
    "2A 094A 000+\n"
    "NNN1\n"
    "FranAais\n"
    "2a 750a 000+\n"
    "EspaAol\n"
    "2.106.000+\n"
    "artAculos\n"
    "a\n"
    "1,530,000+\n"
    "c / c\n"
    "Italiano\n"
    "1.964.000+\n"
    "voci\n"
    "Polski\n"
    "1A 690A 000+\n"
    "haseA\n"
    "PortuguAas\n"
    "1.168.000+\n"
    "artigos\n"
    "Search Wikipedia\n"
    "Afrikaans\n"
    "Shqip\n"
    "U1 U\n"
    "Asturianu\n"
    "AzErbaycanca\n"
    "N3NNo\n"
    "eaea / BAn-lAm-gAo\n"
    "aa34aa2a34\n"
    "NNNoN\n"
    "CatalA\n"
    "AeAtina\n"
    "Cymraeg\n"
    "Dansk\n"
    "Eesti\n"
    "IIIII12I1IoI\n"
    "Esperanto\n"
    "Euskara\n"
    "U3U\n"
    "Galego\n"
    "iei\n"
    "OOOOOOO\n"
    "a1aa aaa\n"
    "Hrvatski\n"
    "Bahasa Indonesia\n"
    "aaa aaaa\n"
    "Ladin\n"
    "Latina\n"
    "LatvieAu\n"
    "LietuviA3\n"
    "Magyar\n"
    "o 3412No\n"
    "Malagasy\n"
    "aaa34a a\n"
    "UU\n"
    "Bahasa Melayu\n"
    "Bahaso Minangkabau\n"
    "aa14aaoaaaaaa\n"
    "Nederlands\n"
    "Norsk (bokmAl)\n"
    "Norsk (nynorsk)\n"
    "34NN 112\n"
    "OEzbekcha / oN\n"
    "OON / QazaqAa / U2U\n"
    "RomAnA\n"
    "Simple English\n"
    "Sinugboanong Binisaya\n"
    "SlovenAina\n"
    "SlovenAAina\n"
    "NNo / Srpski\n"
    "Srpskohrvatski / NNo34NN2NNo\n"
    "Suomi\n"
    "Svenska\n"
    "Kiswahili\n"
    "aaaa a\n"
    "NNN / TatarAa\n"
    "aaa2aaa\n"
    "a a 2a a 2a1a a\n"
    "34O oO\n"
    ;

static const char nova_webcache_hacker_news[] =
    "# Hacker News\n"
    "Titre: Hacker News\n"
    "URL source: https://news.ycombinator.com\n"
    "Capture: 2026-04-13 18:12 UTC\n"
    "Mode: miroir texte de page web reelle pour le navigateur local\n"
    "\n"
    "Hacker News\n"
    "new\n"
    "|\n"
    "past\n"
    "comments\n"
    "ask\n"
    "show\n"
    "jobs\n"
    "submit\n"
    "login\n"
    "1.\n"
    "Nothing Ever Happens: Polymarket bot that always buys No on non-sports markets\n"
    "(\n"
    "github.com/sterlingcrispin\n"
    ")\n"
    "218 points\n"
    "by\n"
    "m-hodges\n"
    "2 hours ago\n"
    "hide\n"
    "79 comments\n"
    "2.\n"
    "The Future of Everything Is Lies, I Guess: Safety\n"
    "aphyr.com\n"
    "107 points\n"
    "aphyr\n"
    "1 hour ago\n"
    "43 comments\n"
    "3.\n"
    "Building a CLI for All of Cloudflare\n"
    "cloudflare.com\n"
    "124 points\n"
    "soheilpro\n"
    "36 comments\n"
    "4.\n"
    "Servo is now available on crates.io\n"
    "servo.org\n"
    "294 points\n"
    "ffin\n"
    "5 hours ago\n"
    "96 comments\n"
    "5.\n"
    "Make Tmux Pretty and Usable (2024)\n"
    "hamvocke.com\n"
    "184 points\n"
    "speckx\n"
    "3 hours ago\n"
    "131 comments\n"
    "6.\n"
    "Tracking down a 25% Regression on LLVM RISC-V\n"
    "kaving.me\n"
    "26 points\n"
    "luu\n"
    "6 comments\n"
    "7.\n"
    "MEMS Array Chip Can Project Video the Size of a Grain of Sand\n"
    "ieee.org\n"
    "38 points\n"
    "bookofjoe\n"
    "9 comments\n"
    "8.\n"
    "All elementary functions from a single binary operator\n"
    "arxiv.org\n"
    "721 points\n"
    "pizza\n"
    "16 hours ago\n"
    "214 comments\n"
    "9.\n"
    "Initial mainline video capture and camera support for Rockchip RK3588\n"
    "collabora.com\n"
    "44 points\n"
    "mfilion\n"
    "4 hours ago\n"
    "11 comments\n"
    "10.\n"
    "Microsoft isn't removing Copilot from Windows 11, it's just renaming it\n"
    "neowin.net\n"
    "187 points\n"
    "bundie\n"
    "122 comments\n"
    "11.\n"
    "US appeals court declares 158-year-old home distilling ban unconstitutional\n"
    "nypost.com\n"
    "216 points\n"
    "t-3\n"
    "137 comments\n"
    "12.\n"
    "Michigan 'digital age' bills pulled after privacy concerns raised\n"
    "thecentersquare.com\n"
    "152 points\n"
    ;

static const char nova_webcache_example_domain[] =
    "# Example Domain\n"
    "Titre: Example Domain\n"
    "URL source: https://example.com\n"
    "Capture: 2026-04-13 18:12 UTC\n"
    "Mode: miroir texte de page web reelle pour le navigateur local\n"
    "\n"
    "Example Domain\n"
    "This domain is for use in documentation examples without needing permission. Avoid use in operations.\n"
    "Learn more\n"
    ;

static const nova_webcache_entry_t nova_webcache_entries[] = {
    {
        "github-home",
        "GitHub",
        "github.com",
        "https://github.com",
        "/webcache/github-home.txt",
        "2026-04-13 18:12 UTC",
        nova_webcache_github_home
    },
    {
        "wikipedia-home",
        "Wikipedia",
        "wikipedia.org",
        "https://www.wikipedia.org",
        "/webcache/wikipedia-home.txt",
        "2026-04-13 18:12 UTC",
        nova_webcache_wikipedia_home
    },
    {
        "hacker-news",
        "Hacker News",
        "news.ycombinator.com",
        "https://news.ycombinator.com",
        "/webcache/hacker-news.txt",
        "2026-04-13 18:12 UTC",
        nova_webcache_hacker_news
    },
    {
        "example-domain",
        "Example Domain",
        "example.com",
        "https://example.com",
        "/webcache/example-domain.txt",
        "2026-04-13 18:12 UTC",
        nova_webcache_example_domain
    },
};

static const int nova_webcache_entry_count = sizeof(nova_webcache_entries) / sizeof(nova_webcache_entries[0]);

#endif
